### PR TITLE
Port to MuseScore 3.x

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Prior to merging this please branch the current master into a 2.x branch

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Hmm, not the 1.x and 2.x version is gone?

**Comment by lasconic** [comment]
Missed your message... Let me revert and give you ownership :)

**Comment by lasconic** [comment]
Actually, I can't transfer it to you since you have a fork.

**Comment by Jojo-Schmitz** [comment]
Can’t you just create a branch „2.x“, then merge my PR into master?

**Comment by lasconic** [comment]
Done

**Comment by Jojo-Schmitz** [comment]
Thanks ;-)

**Pull request merged**
